### ISSUE TITLE
Stream Length Error

### ISSUE THREAD

**Issue by TheTrueShell** [overtools/OWLib#128]
**Describe the bug**
Unable to run the program, running correct command causes Stream Length error.

**To Reproduce**

1. Open in CMD
2. Run Command shown in Logs

**Expected behavior**
List all the heroes

**Logs**
```
`D:\Users\[USERNAME]\Downloads\toolchain-release>DataTool.exe "D:\Program Files DATA\Games\Overwatch" list-heroes
[Core] DataTool v1.58.0.944-git-510ff4936a6797e5705fc2f8c57dec50a868900f
[Core] CommandLine: ["D:\Program Files DATA\Games\Overwatch", "list-heroes"]
[Core] CommandLineFile: D:\Users\[USERNAME]\Downloads\toolchain-release\DataTool.args
[CASC] Text Language: enUS | Speech Language: enUS
[CASC] Overwatch build 1.59.0.0.80550
[CASC] Initializing...
[Manifest] No TRG procedure for build 80550, trying closest version
[Manifest] Using TRG procedure 80111
[CASC] =================
Error initializing CASC!
Please Scan & Repair your game, launch it for a minute, and try the tools again before reporting a bug!
========================
Stream length must be non-negative and less than 2^31 - 1 - origin. (Parameter 'value')
   at System.IO.MemoryStream.set_Position(Int64 value)
   at TACTLib.Core.Product.Tank.ResourceGraph.ParseBlocks(BinaryReader reader, String name) in C:\projects\owlib\TACTLib\TACTLib\Core\Product\Tank\ResourceGraph.cs:line 219
   at TACTLib.Core.Product.Tank.ResourceGraph..ctor(ClientHandler client, Stream stream, String name) in C:\projects\owlib\TACTLib\TACTLib\Core\Product\Tank\ResourceGraph.cs:line 173
   at TACTLib.Core.Product.Tank.ProductHandler_Tank..ctor(ClientHandler client, Stream stream) in C:\projects\owlib\TACTLib\TACTLib\Core\Product\Tank\ProductHandler_Tank.cs:line 146`
```

**Desktop:**
 - OS: Windows 10
 - Overwatch Version: 1.59.0.0.80550
 - Overwatch Region: Europe
 - Overwatch Language: English

**Comment by Js41637** [comment]
Tools are not yet updated for 1.59.
