### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by DarkfireOW** [overtools/OWLib#163]
**Describe the bug**
The datatool is not same version as the game, wich is now in 1.71.1.0.97745a

**Expected behavior**
update the datatool

**Logs**
[CASC] 
Error initializing CASC!
Please Scan & Repair your game, launch it for a minute, and try the tools again before reporting a bug!
Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseUInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.UInt32.Parse(String s)
   at DataTool.Program.InitStorage(Boolean online) in C:\projects\owlib\DataTool\Program.cs:line 268
   at DataTool.Program.Main() in C:\projects\owlib\DataTool\Program.cs:line 144

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Overwatch Version [1.71.1.0.97745a]
 - Overwatch Region [Europe]
 - Overwatch Language [English]

Thanks a lot for your tool, it's amazing "-"

**Comment by SirBitesalot** [comment]
@DarkfireOW The current Version works fine for me. So I think this is already fixed.
