### ISSUE TITLE
DataTool extract-maps King's Row error

### ISSUE THREAD

**Issue by Awpteamoose** [overtools/OWLib#42]
```
DataTool.exe F:\Games\Overwatch extract-maps D:\projects\OWDump
CASC CDN Cache path is C:\Users\Awpteamoose\Downloads\toolchain-release\CascCache
DataTool v1.18.0.330-git-b19e0083fcb441f4bc1051981d4bc0d9ffc5af58
Initializing CASC...
Set language to enUS
Using Overwatch Version 1.18.1.2.42076
Loading APM TactManifest/Win_SPWin_RDEV_LenUS_EExt.apm
Using CMF procedure 42076
Loading APM TactManifest/Win_SPWin_speech_RDEV_LenUS_EExt.apm
Using CMF procedure 42076
Mapping...
Adding Encryption Keys...
Tooling...
Saving map: TEMPLE OF ANUBIS (5B)
Saving map: KING'S ROW (D4)

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DataTool.Helper.EffectParser.<GetChunks>d__6.MoveNext()
   at DataTool.Helper.EffectParser.ProcessAll(Dictionary`2 replacements)
   at DataTool.Helper.EffectParser.Process(EffectInfo effectInfo, KeyValuePair`2 chunk, Dictionary`2 replacements)
   at DataTool.FindLogic.Animation.FindChunked(HashSet`1 existingAnimations, HashSet`1 models, STUGUID animationGUID, Dictionary`2 replacements, UInt64 parentAnim)
   at DataTool.FindLogic.Animation.FindAnimations(HashSet`1 existingAnimations, HashSet`1 models, STUGUID animationGUID, Dictionary`2 replacements, STUGUID skeleton)
   at DataTool.FindLogic.Animation.FindAnimations(HashSet`1 existingAnimations, HashSet`1 models, STUGUID animationGUID, Dictionary`2 replacements, STUGUID skeleton)
   at DataTool.FindLogic.Model.FindModels(HashSet`1 existingModels, STUGUID modelGUID, Dictionary`2 replacements)
   at DataTool.SaveLogic.Map.Save(ICLIFlags toolFlags, STUMap map, UInt64 key, String basePath)
   at DataTool.ToolLogic.Extract.ExtractMaps.GetMaps(ICLIFlags toolFlags)
   at DataTool.ToolLogic.Extract.ExtractMaps.Parse(ICLIFlags toolFlags)
   at DataTool.Program.Main()```

**Comment by Awpteamoose** [comment]
no longer occurs
