### ISSUE TITLE
Crashes when using the * wildcard. 

### ISSUE THREAD

**Issue by Kurty00** [overtools/OWLib#53]
So this happend while I was using extract-unlocks and extract-maps with the * wildcard. 

I think it is running out of RAM... Used about 9,6 GB when this happend:

```
System.ArgumentNullException: The value can not be NULL.
Parametername: input
   at System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   at TankLib.teTexturePayload..ctor(teTexture parent, Stream payloadStream)
   at TankLib.teTexture.LoadPayload(Stream payloadStream)
   at DataTool.SaveLogic.Combo.SaveTexture(ICLIFlags flags, String path, ComboInfo info, UInt64 textureGUID)
   at DataTool.SaveLogic.Combo.SaveMaterial(ICLIFlags flags, String path, ComboInfo info, UInt64 material)
   at DataTool.SaveLogic.Combo.SaveModelLook(ICLIFlags flags, String path, ComboInfo info, UInt64 modelLook)
   at DataTool.SaveLogic.Combo.SaveModel(ICLIFlags flags, String path, ComboInfo info, UInt64 modelGUID)
   at DataTool.SaveLogic.Combo.Save(ICLIFlags flags, String path, ComboInfo info)
   at DataTool.SaveLogic.Unlock.SkinTheme.Save(ICLIFlags flags, String directory, STUSkinBase skin, STUHero hero)
   at DataTool.ToolLogic.Extract.ExtractHeroUnlocks.SaveUnlock(ICLIFlags flags, Unlock unlock, String path, String eventKey, Dictionary`2 config, Dictionary`2 tags, VoiceSet voiceSet, STUHero hero)
   at DataTool.ToolLogic.Extract.ExtractHeroUnlocks.SaveUnlocks(ICLIFlags flags, Unlock[] unlocks, String path, String eventKey, Dictionary`2 config, Dictionary`2 tags, VoiceSet voiceSet, STUHero hero)
   at DataTool.ToolLogic.Extract.ExtractHeroUnlocks.SaveUnlocksForHeroes(ICLIFlags flags, IEnumerable`1 heroes, String basePath, Boolean npc)
   at DataTool.ToolLogic.Extract.ExtractHeroUnlocks.Parse(ICLIFlags toolFlags)
   at DataTool.Program.Main()
```

**Comment by ZingBallyhoo** [comment]
Post the full log.

**Comment by Kurty00** [comment]
Here you go: 
```[Core] DataTool v1.29.0.786-git-d123c36028747ac8da98e1cfef89753f2ef27380
[Core] CommandLine: ["-T=enUS", "-L=enUS", "C:\Program Files (x86)\Overwatch", "extract-unlocks", "D:\Daten\OverwatchExtract", "*"]
[Core] CommandLineFile: D:\Downloads\toolchain-release(1)\DataTool.exe.args
[CASC] Set language to enUS
[CASC] Set speech language to enUS
[CASC] Overwatch build 1.29.0.1.51948
[CASC] Initializing...
[CMF] Using CMF procedure 51948
[CMF] Using CMF procedure 51948
[CASC] Mapping assets...
[CASC] Ready
[Core] Checking ResourceKeys
[Core] Tooling...
Processing unlocks for Reaper
        Extracting skin Blackwatch Reyes
                Finding
                Saving
                Done
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Royal
                Finding
                Saving
                Done
        Extracting skin Blood
                Finding
                Saving
                Done
        Extracting skin Midnight
                Finding
                Saving
                Done
        Extracting skin Moss
                Finding
                Saving
                Done
        Extracting skin Desert
                Finding
                Saving
                Done
        Extracting skin Wight
                Finding
                Saving
                Done
        Extracting skin Mariachi
                Finding
                Saving
                Done
        Extracting skin El Blanco
                Finding
                Saving
                Done
        Extracting skin Nevermore
                Finding
                Saving
                Done
        Extracting skin Plague Doctor
                Finding
                Saving
                Done
        Extracting skin Hellfire
                Finding
                Saving
                Done
        Extracting skin Biker
                Finding
                Saving
                Done
        Extracting skin Pumpkin
                Finding
                Saving
                Done
        Extracting skin Dracula
                Finding
                Saving
                Done
        Extracting skin Shiver
                Finding
                Saving
                Done
        Extracting skin Soldier: 24
                Finding
                Saving
                Done
Processing unlocks for Tracer
        Extracting skin Slipstream
                Finding
                Saving
                Done
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Neon Green
                Finding
                Saving
                Done
        Extracting skin Royal Blue
                Finding
                Saving
                Done
        Extracting skin Hot Pink
                Finding
                Saving
                Done
        Extracting skin Electric Purple
                Finding
                Saving
                Done
        Extracting skin Posh
                Finding
                Saving
                Done
        Extracting skin Sporty
                Finding
                Saving
                Done
        Extracting skin Punk
                Finding
                Saving
                Done
        Extracting skin Ultraviolet
                Finding
                Saving
                Done
        Extracting skin T. Racer
                Finding
                Saving
                Done
        Extracting skin Mach T
                Finding
                Saving
                Done
        Extracting skin Sprinter
                Finding
                Saving
                Done
        Extracting skin Track and Field
                Finding
                Saving
                Done
        Extracting skin Jingle
                Finding
                Saving
                Done
        Extracting skin Rose
                Finding
                Saving
                Done
        Extracting skin Cadet Oxton
                Finding
                Saving
                Done
        Extracting skin Graffiti
                Finding
                Saving
                Done
        Extracting skin Lightning
                Finding
                Saving
                Done
Processing unlocks for Mercy
        Extracting skin Pink
                Finding
                Saving
                Done
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Celestial
                Finding
                Saving
                Done
        Extracting skin Verdant
                Finding
                Saving
                Done
        Extracting skin Orchid
                Finding
                Saving
                Done
        Extracting skin Mist
                Finding
                Saving
                Done
        Extracting skin Cobalt
                Finding
                Saving
                Done
        Extracting skin Amber
                Finding
                Saving
                Done
        Extracting skin Devil
                Finding
                Saving
                Done
        Extracting skin Imp
                Finding
                Saving
                Done
        Extracting skin Valkyrie
                Finding
                Saving
                Done
        Extracting skin Sigrún
                Finding
                Saving
                Done
        Extracting skin Eidgenossin
                Finding
                Saving
                Done
        Extracting skin Winged Victory
                Finding
                Saving
                Done
        Extracting skin Witch
                Finding
                Saving
                Done
        Extracting skin Fortune
                Finding
                Saving
                Done
        Extracting skin Zhuque
                Finding
                Saving
                Done
        Extracting skin Combat Medic Ziegler
                Finding
                Saving
                Done
Processing unlocks for Hanzo
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Azuki
                Finding
                Saving
                Done
        Extracting skin Midori
                Finding
                Saving
                Done
        Extracting skin Kinoko
                Finding
                Saving
                Done
        Extracting skin Sora
                Finding
                Saving
                Done
        Extracting skin Cloud
                Finding
                Saving
                Done
        Extracting skin Dragon
                Finding
                Saving
                Done
        Extracting skin Young Hanzo
                Finding
                Saving
                Done
        Extracting skin Young Master
                Finding
                Saving
                Done
        Extracting skin Okami
                Finding
                Saving
                Done
        Extracting skin Lone Wolf
                Finding
                Saving
                Done
        Extracting skin Kabuki
                Finding
                Saving
                Done
        Extracting skin Demon
                Finding
                Saving
                Done
        Extracting skin Casual
                Finding
                Saving
                Done
        Extracting skin Scion
                Finding
                Saving
                Done
        Extracting skin Cyberninja
                Finding
                Saving
                Done
Processing unlocks for Torbjörn
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Citron
                Finding
                Saving
                Done
        Extracting skin Grön
                Finding
                Saving
                Done
        Extracting skin Blå
                Finding
                Saving
                Done
        Extracting skin Plommon
                Finding
                Saving
                Done
        Extracting skin Woodclad
                Finding
                Saving
                Done
        Extracting skin Cathode
                Finding
                Saving
                Done
        Extracting skin Deadlock
                Finding
                Saving
                Done
        Extracting skin Chopper
                Finding
                Saving
                Done
        Extracting skin Blackbeard
                Finding
                Saving
                Done
        Extracting skin Barbarossa
                Finding
                Saving
                Done
        Extracting skin Magni
                Finding
                Saving
                Done
        Extracting skin Tre Kronor
                Finding
                Saving
                Done
        Extracting skin Viking
                Finding
                Saving
                Done
        Extracting skin Santaclad
                Finding
                Saving
                Done
        Extracting skin Ironclad
                Finding
                Saving
                Done
        Extracting skin Chief Engineer Lindholm
                Finding
                Saving
                Done
        Extracting skin Cybjörn
                Finding
                Saving
                Done
Processing unlocks for Reinhardt
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Copper
                Finding
                Saving
                Done
        Extracting skin Viridian
                Finding
                Saving
                Done
        Extracting skin Brass
                Finding
                Saving
                Done
        Extracting skin Cobalt
                Finding
                Saving
                Done
        Extracting skin Paragon
                Finding
                Saving
                Done
        Extracting skin Bundeswehr
                Finding
                Saving
                Done
        Extracting skin Blackhardt
                Finding
                Saving
                Done
        Extracting skin Bloodhardt
                Finding
                Saving
                Done
        Extracting skin Lionhardt
                Finding
                Saving
                Done
        Extracting skin Stonehardt
                Finding
                Saving
                Done
        Extracting skin Balderich
                Finding
                Saving
                Done
        Extracting skin Greifhardt
                Finding
                Saving
                Done
        Extracting skin Crusader
                Finding
                Saving
                Done
        Extracting skin Gridironhardt
                Finding
                Saving
                Done
        Extracting skin Coldhardt
                Finding
                Saving
                Done
        Extracting skin Wujing
                Finding
                Saving
                Done
        Extracting skin Lieutenant Wilhelm
                Finding
                Saving
                Done
Processing unlocks for Pharah
        Extracting skin Security Chief
                Finding
                Saving
                Done
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Emerald
                Finding
                Saving
                Done
        Extracting skin Amethyst
                Finding
                Saving
                Done
        Extracting skin Titanium
                Finding
                Saving
                Done
        Extracting skin Copper
                Finding
                Saving
                Done
        Extracting skin Anubis
                Finding
                Saving
                Done
        Extracting skin Jackal
                Finding
                Saving
                Done
        Extracting skin Mechaqueen
                Finding
                Saving
                Done
        Extracting skin Raptorion
                Finding
                Saving
                Done
        Extracting skin Thunderbird
                Finding
                Saving
                Done
        Extracting skin Raindancer
                Finding
                Saving
                Done
        Extracting skin Asp
                Finding
                Saving
                Done
        Extracting skin Possessed
                Finding
                Saving
                Done
        Extracting skin Enchanted Armor
                Finding
                Saving
                Done
        Extracting skin Frostbite
                Finding
                Saving
                Done
        Extracting skin Qinglong
                Finding
                Saving
                Done
        Extracting skin Bedouin
                Finding
                Saving
                Done
Processing unlocks for Winston
        Extracting skin BlizzCon 2017
                Finding
                Saving
                Done
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Forest
                Finding
                Saving
                Done
        Extracting skin Atmosphere
                Finding
                Saving
                Done
        Extracting skin Banana
                Finding
                Saving
                Done
        Extracting skin Red Planet
                Finding
                Saving
                Done
        Extracting skin Desert
                Finding
                Saving
                Done
        Extracting skin Horizon
                Finding
                Saving
                Done
        Extracting skin Undersea
                Finding
                Saving
                Done
        Extracting skin Frogston
                Finding
                Saving
                Done
        Extracting skin Explorer
                Finding
                Saving
                Done
        Extracting skin Safari
                Finding
                Saving
                Done
        Extracting skin Catcher
                Finding
                Saving
                Done
        Extracting skin Yeti
                Finding
                Saving
                Done
        Extracting skin Wukong
                Finding
                Saving
                Done
        Extracting skin Specimen 28
                Finding
                Saving
                Done
Processing unlocks for Widowmaker
        Extracting skin Noire
                Finding
                Saving
                Done
        Extracting skin Kerrigan
                Finding
                Saving
                Done
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Ciel
                Finding
                Saving
                Done
        Extracting skin Vert
                Finding
                Saving
                Done
        Extracting skin Nuit
                Finding
                Saving
                Done
        Extracting skin Rose
                Finding
                Saving
                Done
        Extracting skin Winter
                Finding
                Saving
                Done
        Extracting skin Patina
                Finding
                Saving
                Done
        Extracting skin Odile
                Finding
                Saving
                Done
        Extracting skin Odette
                Finding
                Saving
                Done
        Extracting skin Comtesse
                Finding
                Saving
                Done
        Extracting skin Huntress
                Finding
                Saving
                Done
        Extracting skin Nova
                Finding
                Saving
                Done
        Extracting skin Tricolore
                Finding
                Saving
                Done
        Extracting skin Côte d'Azur
                Finding
                Saving
                Done
        Extracting skin Spider
                Finding
                Saving
                Done
        Extracting skin Black Lily
                Finding
                Saving
                Done
        Extracting skin Talon
                Finding
                Saving
                Done
Processing unlocks for Bastion
        Extracting skin Overgrown
                Finding
                Saving
                Done
        Extracting skin BlizzCon 2016
                Finding
                Saving
                Done
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Sky
                Finding
                Saving
                Done
        Extracting skin Meadow
                Finding
                Saving
                Done
        Extracting skin Dawn
                Finding
                Saving
                Done
        Extracting skin Soot
                Finding
                Saving
                Done
        Extracting skin Omnic Crisis
                Finding
                Saving
                Done
        Extracting skin Defense Matrix
                Finding
                Saving
                Done
        Extracting skin Steambot
                Finding
                Saving
                Done
        Extracting skin Gearbot
                Finding
                Saving
                Done
        Extracting skin Antique
                Finding
                Saving
                Done
        Extracting skin Woodbot
                Finding
                Saving
                Done
        Extracting skin Tombstone
                Finding
                Saving
                Done
        Extracting skin Avalanche
                Finding
                Saving
                Done
        Extracting skin Rooster
                Finding
                Saving
                Done
        Extracting skin Null Sector
                Finding
                Saving
                Done
        Extracting skin Dune Buggy
                Finding
                Saving
                Done
        Extracting skin Stealth
                Finding
                Saving
                Done
Processing unlocks for Symmetra
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Hyacinth
                Finding
                Saving
                Done
        Extracting skin Cardamom
                Finding
                Saving
                Done
        Extracting skin Saffron
                Finding
                Saving
                Done
        Extracting skin Technomancer
                Finding
                Saving
                Done
        Extracting skin Regal
                Finding
                Saving
                Done
        Extracting skin Utopaea
                Finding
                Saving
                Done
        Extracting skin Devi
                Finding
                Saving
                Done
        Extracting skin Goddess
                Finding
                Saving
                Done
        Extracting skin Vishkar
                Finding
                Saving
                Done
        Extracting skin Architech
                Finding
                Saving
                Done
        Extracting skin Peacock
                Finding
                Saving
                Done
        Extracting skin Vampire
                Finding
                Saving
                Done
        Extracting skin Dragon
                Finding
                Saving
                Done
        Extracting skin Qipao
                Finding
                Saving
                Done
        Extracting skin Oasis
                Finding
                Saving
                Done
        Extracting skin Magician
                Finding
                Saving
                Done
Processing unlocks for Zenyatta
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Leaf
                Finding
                Saving
                Done
        Extracting skin Water
                Finding
                Saving
                Done
        Extracting skin Earth
                Finding
                Saving
                Done
        Extracting skin Air
                Finding
                Saving
                Done
        Extracting skin Ascendant
                Finding
                Saving
                Done
        Extracting skin Harmonious
                Finding
                Saving
                Done
        Extracting skin Ra
                Finding
                Saving
                Done
        Extracting skin Sunyatta
                Finding
                Saving
                Done
        Extracting skin Djinnyatta
                Finding
                Saving
                Done
        Extracting skin Ifrit
                Finding
                Saving
                Done
        Extracting skin Carbon Fiber
                Finding
                Saving
                Done
        Extracting skin Fastball
                Finding
                Saving
                Done
        Extracting skin Skullyatta
                Finding
                Saving
                Done
        Extracting skin Cultist
                Finding
                Saving
                Done
        Extracting skin Nutcracker
                Finding
                Saving
                Done
        Extracting skin Sanzang
                Finding
                Saving
                Done
Processing unlocks for Genji
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Azurite
                Finding
                Saving
                Done
        Extracting skin Malachite
                Finding
                Saving
                Done
        Extracting skin Ochre
                Finding
                Saving
                Done
        Extracting skin Cinnabar
                Finding
                Saving
                Done
        Extracting skin Carbon Fiber
                Finding
                Saving
                Done
        Extracting skin Chrome
                Finding
                Saving
                Done
        Extracting skin Young Genji
                Finding
                Saving
                Done
        Extracting skin Sparrow
                Finding
                Saving
                Done
        Extracting skin Bedouin
                Finding
                Saving
                Done
        Extracting skin Nomad
                Finding
                Saving
                Done
        Extracting skin Oni
                Finding
                Saving
                Done
        Extracting skin Nihon
                Finding
                Saving
                Done
        Extracting skin Baihu
                Finding
                Saving
                Done
        Extracting skin Blackwatch
                Finding
                Saving
                Done
        Extracting skin Sentai
                Finding
                Saving
                Done
Processing unlocks for Roadhog
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Kiwi
                Finding
                Saving
                Done
        Extracting skin Mud
                Finding
                Saving
                Done
        Extracting skin Sand
                Finding
                Saving
                Done
        Extracting skin Thistle
                Finding
                Saving
                Done
        Extracting skin Stitched
                Finding
                Saving
                Done
        Extracting skin Pigpen
                Finding
                Saving
                Done
        Extracting skin Toa
                Finding
                Saving
                Done
        Extracting skin Islander
                Finding
                Saving
                Done
        Extracting skin Mako
                Finding
                Saving
                Done
        Extracting skin Sharkbait
                Finding
                Saving
                Done
        Extracting skin Butcher
                Finding
                Saving
                Done
        Extracting skin Lacrosse
                Finding
                Saving
                Done
        Extracting skin Junkenstein's Monster
                Finding
                Saving
                Done
        Extracting skin Rudolph
                Finding
                Saving
                Done
        Extracting skin Ice Fisherman
                Finding
                Saving
                Done
        Extracting skin Bajie
                Finding
                Saving
                Done
Processing unlocks for McCree
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Lake
                Finding
                Saving
                Done
        Extracting skin Sage
                Finding
                Saving
                Done
        Extracting skin Wheat
                Finding
                Saving
                Done
        Extracting skin Ebony
                Finding
                Saving
                Done
        Extracting skin On the Range
                Finding
                Saving
                Done
        Extracting skin White Hat
                Finding
                Saving
                Done
        Extracting skin Gambler
                Finding
                Saving
                Done
        Extracting skin Riverboat
                Finding
                Saving
                Done
        Extracting skin Mystery Man
                Finding
                Saving
                Done
        Extracting skin Vigilante
                Finding
                Saving
                Done
        Extracting skin Royal
                Finding
                Saving
                Done
        Extracting skin American
                Finding
                Saving
                Done
        Extracting skin Lifeguard
                Finding
                Saving
                Done
        Extracting skin Van Helsing
                Finding
                Saving
                Done
        Extracting skin Undead
                Finding
                Saving
                Done
        Extracting skin Scrooge
                Finding
                Saving
                Done
        Extracting skin Magistrate
                Finding
                Saving
                Done
        Extracting skin Blackwatch
                Finding
                Saving
                Done
        Extracting skin Sherlock
                Finding
                Saving
                Done
Processing unlocks for Junkrat
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Bleached
                Finding
                Saving
                Done
        Extracting skin Irradiated
                Finding
                Saving
                Done
        Extracting skin Rusted
                Finding
                Saving
                Done
        Extracting skin Drowned
                Finding
                Saving
                Done
        Extracting skin Jailbird
                Finding
                Saving
                Done
        Extracting skin Toasted
                Finding
                Saving
                Done
        Extracting skin Jester
                Finding
                Saving
                Done
        Extracting skin Fool
                Finding
                Saving
                Done
        Extracting skin Scarecrow
                Finding
                Saving
                Done
        Extracting skin Hayseed
                Finding
                Saving
                Done
        Extracting skin Caution
                Finding
                Saving
                Done
        Extracting skin Cricket
                Finding
                Saving
                Done
        Extracting skin Dr. Junkenstein
                Finding
                Saving
                Done
        Extracting skin Beachrat
                Finding
                Saving
                Done
        Extracting skin Firework
                Finding
                Saving
                Done
        Extracting skin Bilgerat
                Finding
                Saving
                Done
Processing unlocks for Zarya
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Taiga
                Finding
                Saving
                Done
        Extracting skin Violet
                Finding
                Saving
                Done
        Extracting skin Brick
                Finding
                Saving
                Done
        Extracting skin Goldenrod
                Finding
                Saving
                Done
        Extracting skin Dawn
                Finding
                Saving
                Done
        Extracting skin Midnight
                Finding
                Saving
                Done
        Extracting skin Industrial
                Finding
                Saving
                Done
        Extracting skin Cybergoth
                Finding
                Saving
                Done
        Extracting skin Siberian Front
                Finding
                Saving
                Done
        Extracting skin Arctic
                Finding
                Saving
                Done
        Extracting skin Barbarian
                Finding
                Saving
                Done
        Extracting skin Champion
                Finding
                Saving
                Done
        Extracting skin Weightlifter
                Finding
                Saving
                Done
        Extracting skin Totally 80's
                Finding
                Saving
                Done
        Extracting skin Frosted
                Finding
                Saving
                Done
        Extracting skin Xuanwu
                Finding
                Saving
                Done
        Extracting skin Cyberian
                Finding
                Saving
                Done
Processing unlocks for Soldier: 76
        Extracting skin Strike Commander Morrison
                Finding
                Saving
                Done
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Olive
                Finding
                Saving
                Done
        Extracting skin Russet
                Finding
                Saving
                Done
        Extracting skin Smoke
                Finding
                Saving
                Done
        Extracting skin Jet
                Finding
                Saving
                Done
        Extracting skin Bone
                Finding
                Saving
                Done
        Extracting skin Golden
                Finding
                Saving
                Done
        Extracting skin Daredevil: 76
                Finding
                Saving
                Done
        Extracting skin Stunt Rider: 76
                Finding
                Saving
                Done
        Extracting skin Commando: 76
                Finding
                Saving
                Done
        Extracting skin Night Ops: 76
                Finding
                Saving
                Done
        Extracting skin Grillmaster: 76
                Finding
                Saving
                Done
        Extracting skin Immortal
                Finding
                Saving
                Done
        Extracting skin Slasher: 76
                Finding
                Saving
                Done
        Extracting skin Alpine: 76
                Finding
                Saving
                Done
        Extracting skin Cyborg: 76
                Finding
                Saving
                Done
        Extracting skin Venom
                Finding
                Saving
                Done
Processing unlocks for Lúcio
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Roxo
                Finding
                Saving
                Done
        Extracting skin Laranja
                Finding
                Saving
                Done
        Extracting skin Vermelho
                Finding
                Saving
                Done
        Extracting skin Azul
                Finding
                Saving
                Done
        Extracting skin Synaesthesia
                Finding
                Saving
                Done
        Extracting skin Auditiva
                Finding
                Saving
                Done
        Extracting skin Ribbit
                Finding
                Saving
                Done
        Extracting skin Hippityhop
                Finding
                Saving
                Done
        Extracting skin Breakaway
                Finding
                Saving
                Done
        Extracting skin Slapshot
                Finding
                Saving
                Done
        Extracting skin Capoeira
                Finding
                Saving
                Done
        Extracting skin Seleção
                Finding
                Saving
                Done
        Extracting skin Striker
                Finding
                Saving
                Done
        Extracting skin Andes
                Finding
                Saving
                Done
        Extracting skin Equalizer
                Finding
                Saving
                Done
        Extracting skin Jazzy
                Finding
                Saving
                Done
        Extracting skin Bitrate
                Finding
                Saving
                Done
Processing unlocks for D.Va
        Extracting skin Nano
                Finding
                Saving
                Done
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Blueberry
                Finding
                Saving
                Done
        Extracting skin Lemon-Lime
                Finding
                Saving
                Done
        Extracting skin Tangerine
                Finding
                Saving
                Done
        Extracting skin Watermelon
                Finding
                Saving
                Done
        Extracting skin Carbon Fiber
                Finding
                Saving
                Done
        Extracting skin White Rabbit
                Finding
                Saving
                Done
        Extracting skin B.Va
                Finding
                Saving
                Done
        Extracting skin Junebug
                Finding
                Saving
                Done
        Extracting skin Junker
                Finding
                Saving
                Done
        Extracting skin Scavenger
                Finding
                Saving
                Done
        Extracting skin Officer
                Finding
                Saving
                Done
        Extracting skin Black Cat
                Finding
                Saving
                Done
        Extracting skin Taegeukgi
                Finding
                Saving
                Done
        Extracting skin Waveracer
                Finding
                Saving
                Done
        Extracting skin Palanquin
                Finding
                Saving
                Done
        Extracting skin Cruiser
                Finding
                Saving
                Done
Processing unlocks for Mei
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Chrysanthemum
                Finding
                Saving
                Done
        Extracting skin Persimmon
                Finding
                Saving
                Done
        Extracting skin Heliotrope
                Finding
                Saving
                Done
        Extracting skin Jade
                Finding
                Saving
                Done
        Extracting skin Earthen
                Finding
                Saving
                Done
        Extracting skin Snow Plum
                Finding
                Saving
                Done
        Extracting skin Rescue Mei
                Finding
                Saving
                Done
        Extracting skin Firefighter
                Finding
                Saving
                Done
        Extracting skin Yeti Hunter
                Finding
                Saving
                Done
        Extracting skin Abominable
                Finding
                Saving
                Done
        Extracting skin Ecopoint: Antarctica
                Finding
                Saving
                Done
        Extracting skin Jiangshi
                Finding
                Saving
                Done
        Extracting skin Pumpkin
                Finding
                Saving
                Done
        Extracting skin Mei-rry
                Finding
                Saving
                Done
        Extracting skin Chang'e
                Finding
                Saving
                Done
        Extracting skin Luna
                Finding
                Saving
                Done
        Extracting skin Pajamei
                Finding
                Saving
                Done
        Extracting skin Beekeeper
                Finding
                Saving
                Done
Processing unlocks for Sombra
        Extracting skin Demon Hunter
                Finding
                Saving
                Done
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Cidro
                Finding
                Saving
                Done
        Extracting skin Incendio
                Finding
                Saving
                Done
        Extracting skin Mar
                Finding
                Saving
                Done
        Extracting skin Noche
                Finding
                Saving
                Done
        Extracting skin Glitch
                Finding
                Saving
                Done
        Extracting skin Virus
                Finding
                Saving
                Done
        Extracting skin Los Muertos
                Finding
                Saving
                Done
        Extracting skin Azúcar
                Finding
                Saving
                Done
        Extracting skin Cyberspace
                Finding
                Saving
                Done
        Extracting skin Augmented
                Finding
                Saving
                Done
        Extracting skin Tulum
                Finding
                Saving
                Done
        Extracting skin Mexicana
                Finding
                Saving
                Done
        Extracting skin Bride
                Finding
                Saving
                Done
        Extracting skin Peppermint
                Finding
                Saving
                Done
        Extracting skin Rime
                Finding
                Saving
                Done
        Extracting skin Talon
                Finding
                Saving
                Done
Processing unlocks for Doomfist
        Extracting skin Classic
                Finding
                Saving
                Done
        Extracting skin Sunset
                Finding
                Saving
                Done
        Extracting skin Lake
                Finding
                Saving
                Done
        Extracting skin Plains
                Finding
                Saving
                Done
        Extracting skin Daisy
                Finding
                Saving
System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: input
   bei System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   bei TankLib.teTexturePayload..ctor(teTexture parent, Stream payloadStream)
   bei TankLib.teTexture.LoadPayload(Stream payloadStream)
   bei DataTool.SaveLogic.Combo.SaveTexture(ICLIFlags flags, String path, ComboInfo info, UInt64 textureGUID)
   bei DataTool.SaveLogic.Combo.SaveMaterial(ICLIFlags flags, String path, ComboInfo info, UInt64 material)
   bei DataTool.SaveLogic.Combo.SaveModelLook(ICLIFlags flags, String path, ComboInfo info, UInt64 modelLook)
   bei DataTool.SaveLogic.Combo.SaveModel(ICLIFlags flags, String path, ComboInfo info, UInt64 modelGUID)
   bei DataTool.SaveLogic.Combo.Save(ICLIFlags flags, String path, ComboInfo info)
   bei DataTool.SaveLogic.Unlock.SkinTheme.Save(ICLIFlags flags, String directory, STUSkinBase skin, STUHero hero)
   bei DataTool.ToolLogic.Extract.ExtractHeroUnlocks.SaveUnlock(ICLIFlags flags, Unlock unlock, String path, String eventKey, Dictionary`2 config, Dictionary`2 tags, VoiceSet voiceSet, STUHero hero)
   bei DataTool.ToolLogic.Extract.ExtractHeroUnlocks.SaveUnlocks(ICLIFlags flags, Unlock[] unlocks, String path, String eventKey, Dictionary`2 config, Dictionary`2 tags, VoiceSet voiceSet, STUHero hero)
   bei DataTool.ToolLogic.Extract.ExtractHeroUnlocks.SaveUnlocksForHeroes(ICLIFlags flags, IEnumerable`1 heroes, String basePath, Boolean npc)
   bei DataTool.ToolLogic.Extract.ExtractHeroUnlocks.Parse(ICLIFlags toolFlags)
   bei DataTool.Program.Main()```

**Comment by ZingBallyhoo** [comment]
Test with just "doomfist|skin=daisy", if that crashes, scan and repair in Battle.net, because your archive is borked. If it doesn't crash, then let me know as something weird must be going on.

**Comment by Kurty00** [comment]
It didn't crash... So something weird is going on...

**Comment by ZingBallyhoo** [comment]
Can you test and post the log with this build? I need some more info and I don't think I will be able to reproduce on my machine. 

[i53-1.zip](https://github.com/overtools/OWLib/files/2535690/i53-1.zip)

**Comment by Kurty00** [comment]
Okay. I will test it out as soon as possible.

**Comment by Kurty00** [comment]
Well... It didn't run into that error this time and with that build... 🤔 
OW-Version: 1.29.0.1.51948
Here is the log for both, the extract-maps and extract-unlocks:
https://data.k00.eu/ul/2018-11-03_23-45-00.txt [Couldn't fit it into this comment because it is too long.]

**Comment by Kurty00** [comment]
Tested that Debug-Build again. Here is what happend:
```DataTool.exe -T=enUS -L=enUS "C:\Program Files (x86)\Overwatch" list-maps
[i53] issue 53 debug build 1
[Core] DataTool v1.29.0.0-git-tanklib
[Core] CommandLine: ["-T=enUS", "-L=enUS", "C:\Program Files (x86)\Overwatch", "list-maps"]
[Core] CommandLineFile: D:\Downloads\i53-1\DataTool.exe.args
[CASC] Set language to enUS
[CASC] Set speech language to enUS
[CASC] Overwatch build 1.31.0.1.53537
[CASC] Initializing...
[APM] Saving cache for Win_SPWin_RDEV_LenUS_EExt
[CASC] Mapping assets...
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei TACTLib.Core.Product.Tank.ProductHandler_Tank..ctor(ClientHandler client, Stream stream) in D:\Code\Repos\overtool\OWLib-main\TACTLib\TACTLib\Core\Product\Tank\ProductHandler_Tank.cs:Zeile 103.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei TACTLib.Core.Product.ProductHandlerFactory.GetHandler(TACTProduct product, ClientHandler client, Stream root) in D:\Code\Repos\overtool\OWLib-main\TACTLib\TACTLib\Core\Product\ProductHandlerFactory.cs:Zeile 17.
   bei TACTLib.Client.ClientHandler..ctor(String basePath, ClientCreateArgs createArgs) in D:\Code\Repos\overtool\OWLib-main\TACTLib\TACTLib\Client\ClientHandler.cs:Zeile 165.
   bei DataTool.Program.InitStorage(Boolean online) in D:\Code\Repos\overtool\OWLib-main\DataTool\Program.cs:Zeile 222.
   bei DataTool.Program.Main() in D:\Code\Repos\overtool\OWLib-main\DataTool\Program.cs:Zeile 134.```

**Comment by Kurty00** [comment]
It happend again. This time with Overwatch build 1.31.0.1.53537 and DataTool v1.31.0.794-git-7e1040677d0ea05b0ea72b1ee2352229f52915c7

You can find the log here:
https://data.k00.eu/ul/201812_lqvO6ejj4o.txt

**Comment by ZingBallyhoo** [comment]
does anyone know if this issue still occurs?

**Comment by Js41637** [comment]
closing this old issue
