### ISSUE TITLE
Decryption fails for build 1.32.0.1.54011

### ISSUE THREAD

**Issue by antonkravc** [overtools/OWLib#55]
**Describe the bug**
Decryption fails for build 1.32.0.1.54011.

**To Reproduce**
This can be reproduced by using any function of the datatool.

**Expected behavior**
Decryption succeeds.

**Logs**
```
[Core] DataTool v1.31.0.796-git-d277a45e5a0537879d5a969e5478c9eaf92e0a03
[Core] CommandLine: ["C:\Program Files (x86)\Overwatch", "list-heroes"]
[Core] CommandLineFile: C:\Users\anton\Downloads\toolchain-release\DataTool.exe.args
[CASC] Overwatch build 1.32.0.1.54011
[CASC] Initializing...
[CMF] No CMF procedure for build 54011, trying closest version
[CMF] Using CMF procedure 53537
[CASC] Fatal - CMF decryption failed. Please update TACTLib.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.BinaryReader.Dispose(Boolean disposing)
   at TACTLib.Core.Product.Tank.ContentManifestFile..ctor(ClientHandler client, Stream stream, String name)
   at TACTLib.Core.Product.Tank.ProductHandler_Tank..ctor(ClientHandler client, Stream stream)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at TACTLib.Core.Product.ProductHandlerFactory.GetHandler(TACTProduct product, ClientHandler client, Stream root)
   at TACTLib.Client.ClientHandler..ctor(String basePath, ClientCreateArgs createArgs)
   at DataTool.Program.InitStorage(Boolean online)
   at DataTool.Program.Main()
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Overwatch Version - 1.32.0.1.54011
 - Overwatch Region - EU
 - Overwatch Language - English

**Comment by Js41637** [comment]
Every new version of the game needs new and updated CMF. This can take time to get. This is not an issue with the tools

>[CASC] Fatal - CMF decryption failed. Please update TACTLib.
