### ISSUE TITLE
error when extract junkenstein map voice

### ISSUE THREAD

**Issue by kaikaiiiiiii** [overtools/OWLib#70]
**Describe the bug**
got an path error when extract junkenstein map voice.

**To Reproduce**

use command:
```
DataTool.exe -L=enUS -T=enUS "f:\Overwatch" --convert-sound=false --convert-lossless-textures=true --skip-models=true --skip-animations=true extract-maps --flatten f:\T1\en *
```

Got an error:

```
System.IO.DirectoryNotFoundException: cant find path “f:\T1\en\Maps\Junkenstein's Revenge\6C9\VoiceSets\00000000013B.05F\The doctor's creations swarmed over the fallen hero, having claimed their first kill. \00000000-00008923-subtitles.txt” part of the path。
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at DataTool.Helper.IO.WriteFile(String text, String filename)
   at DataTool.SaveLogic.Combo.SaveVoiceStimulus(ICLIFlags flags, String path, ComboInfo info, VoiceLineInstanceInfo voiceLineInstanceInfo)
   at DataTool.SaveLogic.Combo.SaveVoiceStimuliInternal(ICLIFlags flags, String path, ComboInfo info, IEnumerable`1 voiceLineInstances, Boolean split)
   at DataTool.SaveLogic.Combo.SaveVoiceSetInternal(ICLIFlags flags, String path, ComboInfo info, UInt64 voiceSet)
   at  DataTool.SaveLogic.Combo.SaveAllVoiceSets(ICLIFlags flags, String path, ComboInfo soundInfo)
   at  DataTool.SaveLogic.Map.Save(ICLIFlags flags, STUMapHeader mapHeader, UInt64 key, String basePath)
   at  DataTool.ToolLogic.Extract.ExtractMaps.SaveMaps(ICLIFlags toolFlags)
   at  DataTool.Program.Main()
```

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Overwatch Version 1.39
 - Overwatch Language English+Chinese

**Additional context**
Guess the line text makes the full path too long in windows.

Any parameter to walkaround this? For example, don't add line text to filename, just put it in to that txt file.

**Comment by Js41637** [comment]
rip, there is no params at the moment, will fix soon.

**Comment by Js41637** [comment]
This will be fixed in the next release, also there will be a flag to disable subtitles from being extracted.

**Comment by kaikaiiiiiii** [comment]
Got. Thanks.

**Comment by ZingBallyhoo** [comment]
Fixed
https://ci.appveyor.com/project/yukimono/owlib/builds/27025653/artifacts
