### ISSUE TITLE
TACTLib.Core.BLTEDecoderException: frame header mismatch (bad BLTE file)

### ISSUE THREAD

**Issue by aqiank** [overtools/OWLib#85]
Hi, I'm new to this tool. I'm not sure if this is a bug or I just don't know how to use it so I'm creating a blank issue.

I tried to extract hero voice using the command seen in the output below but it seems like it was unable to do it. I believe I'm using the latest versions of DataTool and Overwatch which I have played for a bit.

This is the output:
```
C:\Users\aqian\Downloads\datatool>DataTool.exe "C:\Program Files (x86)\Overwatch" extract-hero-voice C:\Users\aqian\Downloads\datatool\voices "Baptiste|voiceline=*"
[Core] DataTool v1.50.0.878-git-14cc6c1bce8898083a3a1bbdd238d6185ae7386e
[Core] CommandLine: ["C:\Program Files (x86)\Overwatch", "extract-hero-voice", "C:\Users\aqian\Downloads\datatool\voices", "Baptiste|voiceline=*"]
[Core] CommandLineFile: C:\Users\aqian\Downloads\datatool\DataTool.exe.args
[CASC] Text Language: enUS | Speech Language: jaJP
[CASC] Overwatch build 1.50.0.0.71255
[CASC] Initializing...
[Manifest] Using TRG procedure 70665 for Win_SPWin_RDEV_EExt.trg
[Manifest] Using CMF procedure 70665 for Win_SPWin_RDEV_LjaJP_speech_EExt.cmf
[Manifest] Using CMF procedure 70665 for Win_SPWin_RDEV_EExt.cmf
[Manifest] Using CMF procedure 70665 for Win_SPWin_RDEV_LenUS_text_EExt.cmf
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> TACTLib.Core.BLTEDecoderException: frame header mismatch (bad BLTE file)
   at TACTLib.Core.BLTEStream.Init()
   at TACTLib.Client.ClientHandler.OpenEKey(CKey key)
   at TACTLib.Client.ClientHandler.OpenCKey(CKey key)
   at TACTLib.Core.Product.Tank.ProductHandler_Tank.OpenBundle(UInt64 bundleGuid)
   at TACTLib.Core.Product.Tank.ProductHandler_Tank.DoBundleLookupHack()
   at TACTLib.Core.Product.Tank.ProductHandler_Tank..ctor(ClientHandler client, Stream stream)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at TACTLib.Core.Product.ProductHandlerFactory.GetHandler(TACTProduct product, ClientHandler client, Stream root)
   at TACTLib.Client.ClientHandler..ctor(String basePath, ClientCreateArgs createArgs)
   at DataTool.Program.InitStorage(Boolean online)
   at DataTool.Program.Main()
```

Do you have any idea what went wrong?

**Comment by PistonFX** [comment]
Try scan and repair. If that doesn't help, try playing the game for a bit

**Comment by Js41637** [comment]
Yep try a scan and repair and play the game for a minute and try again. Overwatch is weird sometimes. Also you can join the Discord if you need more help. Link in the readme.

**Comment by aqiank** [comment]
I have tried scan and repair and played one match. After that, it still reports the same error.

**Comment by ZingBallyhoo** [comment]
`[CASC] Text Language: enUS | Speech Language: jaJP`

either set to your current game language, or switch to jsJP and scan and repair

**Comment by aqiank** [comment]
@ZingBallyhoo You mean speech language to enUS? I want jaJP though. I have tried with the `-T=jaJP` flag as well. Could you explain what is scan and repaint is?

**Comment by ZingBallyhoo** [comment]
its the word repair but autocorrected. try setting both language settings as jaJP too

**Comment by aqiank** [comment]
I have done scan and repair again but it's still the same. I've also set game text language and speech language to English. Then I used enUS for both -L and -T but it still cannot process it. You can see the output below.

```
DataTool.exe -L=enUS -T=enUS "C:\Program Files (x86)\Overwatch" extract-hero-voice C:\Users\aqian\Downloads\datatool\voices "Baptiste|voiceline=*"
[Core] DataTool v1.50.0.878-git-14cc6c1bce8898083a3a1bbdd238d6185ae7386e
[Core] CommandLine: ["-L=enUS", "-T=enUS", "C:\Program Files (x86)\Overwatch", "extract-hero-voice", "C:\Users\aqian\Downloads\datatool\voices", "Baptiste|voiceline=*"]
[Core] CommandLineFile: C:\Users\aqian\Downloads\datatool\DataTool.exe.args
[CASC] Text Language: enUS | Speech Language: enUS
[CASC] Overwatch build 1.50.0.0.71255
[CASC] Initializing...
System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\Overwatch\data\casc\data\0000000039.idx' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at TACTLib.Container.ContainerHandler.LoadIndexFile(String file, Int32 bucketIndex)
   at TACTLib.Container.ContainerHandler.LoadIndexFiles()
   at TACTLib.Client.ClientHandler..ctor(String basePath, ClientCreateArgs createArgs)
   at DataTool.Program.InitStorage(Boolean online)
   at DataTool.Program.Main()
```

**Comment by ZingBallyhoo** [comment]
that isn't the same error. close battle.net and the game

**Comment by aqiank** [comment]
My bad. Here you go:

```
C:\Users\aqian\Downloads\datatool>DataTool.exe -L=enUS -T=enUS "C:\Program Files (x86)\Overwatch" extract-hero-voice C:\Users\aqian\Downloads\datatool\voices "Baptiste|voiceline=*"
[Core] DataTool v1.50.0.878-git-14cc6c1bce8898083a3a1bbdd238d6185ae7386e
[Core] CommandLine: ["-L=enUS", "-T=enUS", "C:\Program Files (x86)\Overwatch", "extract-hero-voice", "C:\Users\aqian\Downloads\datatool\voices", "Baptiste|voiceline=*"]
[Core] CommandLineFile: C:\Users\aqian\Downloads\datatool\DataTool.exe.args
[CASC] Text Language: enUS | Speech Language: enUS
[CASC] Overwatch build 1.50.0.0.71255
[CASC] Initializing...
[Manifest] Using TRG procedure 70665 for Win_SPWin_RDEV_EExt.trg
[Manifest] Using CMF procedure 70665 for Win_SPWin_RDEV_EExt.cmf
[Manifest] Using CMF procedure 70665 for Win_SPWin_RDEV_LenUS_speech_EExt.cmf
[Manifest] Using CMF procedure 70665 for Win_SPWin_RDEV_LenUS_text_EExt.cmf
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> TACTLib.Core.BLTEDecoderException: frame header mismatch (bad BLTE file)
   at TACTLib.Core.BLTEStream.Init()
   at TACTLib.Client.ClientHandler.OpenEKey(CKey key)
   at TACTLib.Client.ClientHandler.OpenCKey(CKey key)
   at TACTLib.Core.Product.Tank.ProductHandler_Tank.OpenBundle(UInt64 bundleGuid)
   at TACTLib.Core.Product.Tank.ProductHandler_Tank.DoBundleLookupHack()
   at TACTLib.Core.Product.Tank.ProductHandler_Tank..ctor(ClientHandler client, Stream stream)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at TACTLib.Core.Product.ProductHandlerFactory.GetHandler(TACTProduct product, ClientHandler client, Stream root)
   at TACTLib.Client.ClientHandler..ctor(String basePath, ClientCreateArgs createArgs)
   at DataTool.Program.InitStorage(Boolean online)
   at DataTool.Program.Main()
```

**Comment by ZingBallyhoo** [comment]
this is literally impossible, the game can't work in this state. make sure battle.net is updated, scan and repair, play the game for a while, then try the tool

**Comment by aqiank** [comment]
@ZingBallyhoo I have done those steps as mentioned in my previous messages.

**Comment by ZingBallyhoo** [comment]
we've seen this issue hundreds of times and every time its fixed by doing a scan and repair, and also possibly running the game. i don't know how i can help u with this further.

try follow these steps below
1. open bnet
2. set text and speech language to enUS
3. scan and repair
4. run game and play for a bit
5. run tool

**Comment by aqiank** [comment]
Okay, I suppose it is unsolvable since I have already tried those steps. I'm going to close this issue since we are just going round and round with the solution. Thanks!
