### ISSUE TITLE
extract-hero-convo commands reports error

### ISSUE THREAD

**Issue by kaikaiiiiiii** [overtools/OWLib#86]
**Describe the bug**

COMMANDS:
tools\DataTool.exe -L=enUS -T=enUS "C:\Program Files (x86)\Overwatch" --raw-sound=true --convert-lossless-textures=true --skip-models=true --skip-animations=true extract-hero-convo .\Extract\ *

```
[Combo] Async exception: System.IO.IOException: file “F:\owwork\TCExtract1\en\HeroConvo\Ashe\000000000408.0D0\4\000000054FC6.0B2.wem” accessed by another process, while this process can't access this file (正由另一进程使用，因此该进程无法访问此)。
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Bool ean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at DataTool.Helper.IO.WriteFile(Stream stream, String filename)
   at DataTool.SaveLogic.Combo.SaveSoundFileTask(ICLIFlags flags, String directory, SoundFileAsset soundFileInfo, String name)
   at DataTool.SaveLogic.Combo.SaveContext.<>c__DisplayClass7_0.<AddTask>b__0()
[Combo] Async exception: System.IO.IOException: file “F:\owwork\TCExtract1\en\HeroConvo\Ashe\000000000407.0D0\3\000000054FB4.0B2.wem” accessed by another process, while this process can't access this file (正由另一进程使用，因此该进程无法访问此)。
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Bool ean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at DataTool.Helper.IO.WriteFile(Stream stream, String filename)
   at DataTool.SaveLogic.Combo.SaveSoundFileTask(ICLIFlags flags, String directory, SoundFileAsset soundFileInfo, String name)
   at DataTool.SaveLogic.Combo.SaveContext.<>c__DisplayClass7_0.<AddTask>b__0()
[Combo] Async exception: System.IO.IOException: file “F:\owwork\TCExtract1\en\HeroConvo\Ashe\000000000408.0D0\2\000000054FC5.0B2.wem” accessed by another process, while this process can't access this file (正由另一进程使用，因此该进程无法访问此)。
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Bool ean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at DataTool.Helper.IO.WriteFile(Stream stream, String filename)
   at DataTool.SaveLogic.Combo.SaveSoundFileTask(ICLIFlags flags, String directory, SoundFileAsset soundFileInfo, String name)
   at DataTool.SaveLogic.Combo.SaveContext.<>c__DisplayClass7_0.<AddTask>b__0()
```

Both in enUS & zhCN the commands report same error, and the client actually don't be accessed by any other process.

Almost every hero has this error.

**Expected behavior**

Extract files as other commands.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 64bit
 - Overwatch Version 1.50.1.71344
 - Overwatch Region enUS & zhCN
 - Overwatch Language enUS & zhCN

**Additional context**

**Comment by ZingBallyhoo** [comment]
may be an issue cause by antivirus software taking exclusive access to a file....?
