### ISSUE TITLE
extract-maps reports error

### ISSUE THREAD

**Issue by kaikaiiiiiii** [overtools/OWLib#87]
**Describe the bug**
Command:

tools\DataTool.exe -L=zhCN -T=zhCN "C:\Program Files (x86)\Overwatch" --raw-sound=true --convert-lossless-textures=true --skip-models=true --skip-animations=true extract-maps .\TCExtract1\cn *

In some maps it reports error.

```
[Combo] Async exception: System.Collections.Generic.KeyNotFoundException: 给定关键字不在字典中。(given keyword not in dictionary)
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DataTool.SaveLogic.Combo.GetSVCELines(EffectInfo effectInfo, ComboInfo info)
   at DataTool.SaveLogic.Combo.SaveEffectExtras(ICLIFlags flags, String path, SaveContext info, EffectInfo effectInfo, Dictionary`2& svceLines)
   at DataTool.SaveLogic.Combo.SaveEffect(ICLIFlags flags, String path, SaveContext context, UInt64 effect)
   at DataTool.SaveLogic.Combo.SaveContext.<>c__DisplayClass7_0.<AddTask>b__0()
```

**Expected behavior**

Extract all map files.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 64bit
 - Overwatch Version 1.50.1.71344
 - Overwatch Region enUS & zhCN
 - Overwatch Language enUS & zhCN

**Additional context**

**Comment by ZingBallyhoo** [comment]
this should be fixed now
