### ISSUE TITLE
"System.IO.EndOfStreamException: Unable to read beyond the end of the stream."

### ISSUE THREAD

**Issue by doormattt** [overtools/OWLib#91]
**Describe the bug**
Command: datatool "D:\Overwatch\" extract-unlocks "D:\overwatch ports\models" Echo

**Expected behavior**
Extract Echo's model and textures.

**Logs**
[Core] DataTool v1.52.0.883-git-c2599fd0b3ed7a5b68ea1b4b9258a6e78de54cd4
[Core] CommandLine: ["D:\Overwatch", "extract-unlocks", "D:\overwatch ports\models", "Echo"]
[Core] CommandLineFile: D:\overwatch ports\DataTool\DataTool.exe.args
[CASC] Text Language: enUS | Speech Language: enUS
[CASC] Overwatch build 1.52.0.0.73258
[CASC] Initializing...
[Manifest] Using TRG procedure 73258 for Win_SPWin_RDEV_EExt.trg
[Manifest] Using CMF procedure 73258 for Win_SPWin_RDEV_EExt.cmf
[Manifest] Using CMF procedure 73258 for Win_SPWin_RDEV_LenUS_speech_EExt.cmf
[Manifest] Using CMF procedure 73258 for Win_SPWin_RDEV_LenUS_text_EExt.cmf
[CASC] Ready
[Core] Checking ResourceKeys
[Core] Tooling...
Processing unlocks for Echo
        Extracting skin Classic
                Finding
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at TankLib.STU.STUInstance_Info.Deserialize(BinaryReader reader)
   at TankLib.STU.STUBag`1.Deserialize(BinaryReader reader)
   at TankLib.STU.teStructuredData.DeserializeV2(BinaryReader reader)
   at TankLib.STU.teStructuredData..ctor(Stream stream, Boolean keepOpen)
   at DataTool.Helper.STUHelper.OpenSTUSafe(UInt64 key)
   at DataTool.Helper.STUHelper.GetInstance[T](UInt64 key)
   at DataTool.FindLogic.Combo.Find(ComboInfo info, UInt64 guid, Dictionary`2 replacements, ComboContext context)
   at DataTool.FindLogic.Combo.Find(ComboInfo info, UInt64 guid, Dictionary`2 replacements, ComboContext context)
   at DataTool.FindLogic.Combo.Find(ComboInfo info, UInt64 guid, Dictionary`2 replacements, ComboContext context)
   at DataTool.SaveLogic.Unlock.SkinTheme.Save(ICLIFlags flags, String directory, STUSkinBase skin, STUHero hero)
   at DataTool.ToolLogic.Extract.ExtractHeroUnlocks.SaveUnlock(ICLIFlags flags, Unlock unlock, String path, String eventKey, Dictionary`2 config, Dictionary`2 tags, VoiceSet voiceSet, STUHero hero)
   at DataTool.ToolLogic.Extract.ExtractHeroUnlocks.SaveUnlocks(ICLIFlags flags, Unlock[] unlocks, String path, String eventKey, Dictionary`2 config, Dictionary`2 tags, VoiceSet voiceSet, STUHero hero)
   at DataTool.ToolLogic.Extract.ExtractHeroUnlocks.SaveUnlocksForHeroes(ICLIFlags flags, IEnumerable`1 heroes, String basePath, Boolean npc)
   at DataTool.ToolLogic.Extract.ExtractHeroUnlocks.Parse(ICLIFlags toolFlags)
   at DataTool.Program.Main()

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Overwatch Version: 1.52.0.0.73258
 - Overwatch Region: Europe
 - Overwatch Language: English

**Additional context**
I've tried extracting a few other heroes (specifically tracer, mcree, mercy and zenyatta) and got the same error with them, so i'm assuming this is happening with every hero. I'm not exactly sure what could be causing this as both Overwatch and the datatool are up to date as far as I know, and it was also working fine a few months ago.

**Comment by ZingBallyhoo** [comment]
this is a known issue be I'm working on it

**Comment by ZingBallyhoo** [comment]
fixed https://ci.appveyor.com/api/buildjobs/v4tb9y6oeblj4tfl/artifacts/dist%2Ftoolchain-release.zip
