### ISSUE TITLE
error when extracting maps?

### ISSUE THREAD

**Issue by Luke-L** [overtools/OWLib#95]
Array dimensions exceeded supported range.
   at TankLib.teMapPlaceableEntity.Read(BinaryReader reader) in C:\projects\owlib\TankLib\teMapChunk.cs:line 245
   at TankLib.teMapPlaceableManager.CreateType(CommonStructure commonStructure, BinaryReader reader) in C:\projects\owlib\TankLib\teMapChunk.cs:line 491
   at TankLib.teMapPlaceableData.Read(BinaryReader reader) in C:\projects\owlib\TankLib\teMapChunk.cs:line 103
   at TankLib.teMapChunk..ctor(Stream stream) in C:\projects\owlib\TankLib\teMapChunk.cs:line 24
   at DataTool.SaveLogic.Map.GetPlaceableData(STUMapHeader map, Byte type) in C:\projects\owlib\DataTool\SaveLogic\Map.cs:line 386
   at DataTool.SaveLogic.Map.Save(ICLIFlags flags, MapHeader mapInfo, STUMapHeader mapHeader, UInt64 key, String basePath) in C:\projects\owlib\DataTool\SaveLogic\Map.cs:line 292
   at DataTool.ToolLogic.Extract.ExtractMaps.SaveMaps(ICLIFlags toolFlags) in C:\projects\owlib\DataTool\ToolLogic\Extract\ExtractMaps.cs:line 62
   at DataTool.Program.Main() in C:\projects\owlib\DataTool\Program.cs:line 161

[OWET] Exited with code 4294967295

**Comment by Js41637** [comment]
This was just fixed. Download new version :)

**Comment by Luke-L** [comment]
> This was just fixed. Download new version :)

thanks. bit of a dumb question but how do i do that? :/

**Comment by Js41637** [comment]
How did you download the current version? There is information here about how to download the tools. https://github.com/overtools/OWLib/releases/tag/release-info

**Comment by Luke-L** [comment]
> How did you download the current version? There is information here about how to download the tools. https://github.com/overtools/OWLib/releases/tag/release-info

I dont even remember haha, i downloaded it like 6mo ago. also im using OWET2 with DataTool. do i need to update both?

**Comment by Js41637** [comment]
I don't know, we don't use the GUIs or officially support them.
